### ISSUE TITLE
Possible to close a message.on?

### ISSUE THREAD

**Issue by plttn** [tal/slackr-bot#1]
I'm chaining commands with my bot, and right now I have it only recognizing commands directed to it, but it then prompts the user without recognizing the prefix, however then that means that it will keep listening for all prefixed commands.

(basically I've got a message.on matching everything inside of a message.on only matching mentions of my bot. once the everything connection opens, I can't close it to make it only watch for mentions again)

**Comment by tal** [comment]
Hrm, makes sense. Should definitely be an "off" command.
